function(bsdl_read_test_manifest manifest prefix)
    file(STRINGS "${manifest}" lines)
    set(names)
    set(arguments)
    set(name)
    set(args)
    set(threshold)
    foreach(line IN LISTS lines)
        string(STRIP "${line}" stripped)
        if(stripped STREQUAL "" OR stripped MATCHES "^#")
            continue()
        endif()
        if(line MATCHES "^[ \t]+")
            if("${name}" STREQUAL "" OR "${args}" STREQUAL "")
                message(FATAL_ERROR "Unexpected continuation in ${manifest}: ${line}")
            endif()
            string(APPEND args " ${stripped}")
        elseif(stripped MATCHES "^\\[.+\\]$")
            if(NOT "${name}" STREQUAL "")
                if("${args}" STREQUAL "")
                    message(FATAL_ERROR "Test '${name}' in ${manifest} has no args entry")
                endif()
                list(APPEND names "${name}")
                list(APPEND arguments "${args}")
                if(NOT "${threshold}" STREQUAL "")
                    set(${prefix}_THRESHOLD_${name} "${threshold}" PARENT_SCOPE)
                endif()
            endif()
            string(LENGTH "${stripped}" name_length)
            math(EXPR name_length "${name_length} - 2")
            string(SUBSTRING "${stripped}" 1 ${name_length} name)
            set(args)
            set(threshold)
        elseif(stripped MATCHES "^args[ \t]*=")
            if("${name}" STREQUAL "" OR NOT "${args}" STREQUAL "")
                message(FATAL_ERROR "Invalid args entry in ${manifest}: ${line}")
            endif()
            string(REGEX REPLACE "^args[ \t]*=[ \t]*" "" args "${stripped}")
            if("${args}" STREQUAL "")
                message(FATAL_ERROR "Empty args entry in ${manifest}: ${line}")
            endif()
        elseif(stripped MATCHES "^threshold[ \t]*=")
            if("${name}" STREQUAL "" OR NOT "${threshold}" STREQUAL "")
                message(FATAL_ERROR "Invalid threshold entry in ${manifest}: ${line}")
            endif()
            string(REGEX REPLACE "^threshold[ \t]*=[ \t]*" "" threshold "${stripped}")
            if("${threshold}" STREQUAL "")
                message(FATAL_ERROR "Empty threshold entry in ${manifest}: ${line}")
            endif()
        else()
            message(FATAL_ERROR "Invalid test manifest entry in ${manifest}: ${line}")
        endif()
    endforeach()
    if(NOT "${name}" STREQUAL "")
        if("${args}" STREQUAL "")
            message(FATAL_ERROR "Test '${name}' in ${manifest} has no args entry")
        endif()
        list(APPEND names "${name}")
        list(APPEND arguments "${args}")
        if(NOT "${threshold}" STREQUAL "")
            set(${prefix}_THRESHOLD_${name} "${threshold}" PARENT_SCOPE)
        endif()
    endif()
    set(${prefix}_NAMES "${names}" PARENT_SCOPE)
    set(${prefix}_ARGUMENTS "${arguments}" PARENT_SCOPE)
endfunction()